### ISSUE TITLE
Correction?

### ISSUE THREAD

**Issue by adityajain15** [mattdesl/workshop-webgl-glsl#2]
Hi Matt,

in `workshop-webgl-glsl/guides/glsl-syntax.md `

shouldn't `vec2 rgb = myRGBA.rgb;` (bottom of the page)
instead be `vec3 rgb = myRGBA.rgb;`?

**Comment by mattdesl** [comment]
Yes, you are right! Thanks for pointing that out. :smile:

**Comment by adityajain15** [comment]
No worries, thank you for creating this resource :)
